---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: force-web1
  labels:
    app: force
    layer: application
    component: web
    spot-allowed: false
    app.kubernetes.io/version: staging
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: force
      layer: application
      component: web
      spot-allowed: false
  template:
    metadata:
      labels:
        app: force
        layer: application
        component: web
        spot-allowed: false
        app.kubernetes.io/version: staging
      name: force-web1
      namespace: default
    spec:
      containers:
      - name: force-web1
        env:
        - name: PORT
          value: '5000'
        - name: DD_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PAGE_CACHE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEEPALIVE_TIMEOUT_SECONDS
          value: '95'
        - name: HEADERS_TIMEOUT_SECONDS
          value: '105'
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        envFrom:
        - configMapRef:
            name: force-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:staging
        imagePullPolicy: Always
        ports:
        - name: force-http
          containerPort: 5000
        readinessProbe:
          httpGet:
            port: force-http
            path: /system/up
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 1Gi
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: force-web2
  labels:
    app: force
    layer: application
    component: web
    spot-allowed: true
    app.kubernetes.io/version: staging
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: force
      layer: application
      component: web
      spot-allowed: true
  template:
    metadata:
      labels:
        app: force
        layer: application
        component: web
        spot-allowed: true
        app.kubernetes.io/version: staging
      name: force-web2
      namespace: default
    spec:
      containers:
      - name: force-web2
        env:
        - name: PORT
          value: '5000'
        - name: DD_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PAGE_CACHE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEEPALIVE_TIMEOUT_SECONDS
          value: '95'
        - name: HEADERS_TIMEOUT_SECONDS
          value: '105'
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        envFrom:
        - configMapRef:
            name: force-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:staging
        imagePullPolicy: Always
        ports:
        - name: force-http
          containerPort: 5000
        readinessProbe:
          httpGet:
            port: force-http
            path: /system/up
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 1Gi
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      tolerations:
        - key: reserved
          operator: Equal
          value: spot
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
                - foreground-spot
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground-spot
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: force-web2
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: force-web2
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: force
    component: web
    layer: application
  name: force-web-internal
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: force-http
    targetPort: force-http
  selector:
    app: force
    layer: application
    component: web
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: force
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ cloudflareIpSourceRanges|join(',') }}
spec:
  ingressClassName: nginx
  rules:
  - host: staging.artsy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: force-web-internal
          servicePort: force-http
